version: '3'
services:
  dtorrent:
    image: ${IMAGE_SEEDBOX}
    environment:
      MYSQL_HOST: maria
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      STORAGE: .data
    ports:
      - 127.0.0.1:8090:8090
      - 127.0.0.1:8091:8091
    volumes:
      - ${STORAGE}/dtorrent/downloaded:/var/app/.data/dtorrent/downloaded
      - ${STORAGE}/dtorrent/torrent:/var/app/.data/dtorrent/torrent
    links:
      - maria
      - rtorrent

  rtorrent:
    image: ${IMAGE_RTORRENT_DEAMON}
    restart: always
    volumes:
      - ${STORAGE}/dtorrent/downloaded:/var/rtorrent/downloaded
      - ${STORAGE}/dtorrent/torrent:/var/rtorrent/torrents
      - ${STORAGE}/dtorrent/logs:/var/rtorrent/logs

  maria:
    image: mariadb:10.1.23
    volumes:
      - ${STORAGE}/mariadb:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}