version: '3'

networks:
  seedbox:
    external:
      name: seedbox

services:
  seedbox-api:
    build: .
    env_file: .env
    restart: always
    ports:
      - 127.0.0.1:${API_PORT}:${API_PORT}
      - 127.0.0.1:${WEBSOCKET_PORT}:${WEBSOCKET_PORT}
    volumes:
      - .:/var/app/
      - ../dtorrent:/var/app/node_modules/dtorrent
    command: 'npm run start-dev'
    networks:
      - seedbox

  rtorrent-daemon:
    image: ${IMAGE_RTORRENT_DEAMON}
    restart: always
    ports:
      - 8089:80
    volumes:
      - ${STORAGE}/dtorrent/downloaded:/var/rtorrent/downloaded
      - ${STORAGE}/dtorrent/torrent:/var/rtorrent/torrents
      - ${STORAGE}/dtorrent/logs:/var/rtorrent/logs
    networks:
      - seedbox

  seedbox-maria:
    image: mariadb:10.3
    volumes:
      - ${STORAGE}/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - seedbox
