version: '3'
services:
  dtorrent:
    build: .
    environment:
      RTORRENT_HOST: rtorrent
      RTORRENT_PORT: 80
      RTORRENT_PATH: /RPC2
      MYSQL_HOST: maria
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_CONNECTION_STRING: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@maria/${MYSQL_DATABASE}
    ports:
      - 127.0.0.1:8090:${API_PORT}
      - 127.0.0.1:8091:${WS_PORT}
    volumes:
      - ${STORAGE}/dtorrent/downloaded:/var/app/.data/dtorrent/downloaded
    links:
      - maria
      - rtorrent

  rtorrent:
    image: ${IMAGE_RTORRENT_DEAMON}
    restart: always
    ports:
      - 8888:80
    volumes:
      - ${STORAGE}/dtorrent/downloaded:/var/rtorrent/downloaded
      - ${STORAGE}/dtorrent/torrent:/var/rtorrent/torrents
      - ${STORAGE}/dtorrent/logs:/var/rtorrent/logs

  maria:
    image: mariadb:10.1.23
    ports:
      - 3306:3306
    volumes:
      - ${STORAGE}/mariadb:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}