version: '3'
services:
  rtorrent:
    image: rtorrent-daemon:0.0.1
    restart: always
    volumes:
      - ${STORAGE}/downloaded:/var/rtorrent/downloaded
      - ${STORAGE}/torrent:/var/rtorrent/torrents
      - ${STORAGE}/logs:/var/rtorrent/logs

  mongo:
    image: mongo:latest
    volumes:
      - ${STORAGE}/mongo:/data/db

  dtorrent:
    build: .
    environment:
      RTORRENT_HOST: 'rtorrent'
      RTORRENT_PORT: 80
      RTORRENT_PATH: '/RPC2'
      MONGO_HOST: 'mongo'
      MONGO_PORT: 27017
    links:
      - rtorrent
      - mongo